// <auto-generated />
using Colaborador.Infra.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Colaborador.Infra.EF.Migrations
{
    [DbContext(typeof(ColaboradorContext))]
    [Migration("20210605092610_exclusao_coluna_funcao_nome")]
    partial class exclusao_coluna_funcao_nome
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Colaborador.Business.Models.ColaboradorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Colaborador");
                });

            modelBuilder.Entity("Colaborador.Business.Models.ColaboradorModel", b =>
                {
                    b.OwnsOne("Colaborador.Domain.ValueObjects.CPF", "ColaboradorCPF", b1 =>
                        {
                            b1.Property<int>("ColaboradorModelId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("NumeroCPF")
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("NumeroCPF");

                            b1.HasKey("ColaboradorModelId");

                            b1.ToTable("Colaborador");

                            b1.WithOwner()
                                .HasForeignKey("ColaboradorModelId");
                        });

                    b.OwnsOne("Colaborador.Domain.ValueObjects.ColaboradorFuncao", "Funcao", b1 =>
                        {
                            b1.Property<int>("ColaboradorModelId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("FuncaoId")
                                .HasColumnType("int")
                                .HasColumnName("FuncaoId");

                            b1.HasKey("ColaboradorModelId");

                            b1.ToTable("Colaborador");

                            b1.WithOwner()
                                .HasForeignKey("ColaboradorModelId");
                        });

                    b.OwnsOne("Colaborador.Domain.ValueObjects.ColaboradorNome", "Nome", b1 =>
                        {
                            b1.Property<int>("ColaboradorModelId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("PrimeiroNome")
                                .HasMaxLength(30)
                                .HasColumnType("varchar(30)")
                                .HasColumnName("PrimeiroNome");

                            b1.Property<string>("Sobrenome")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Sobrenome");

                            b1.HasKey("ColaboradorModelId");

                            b1.ToTable("Colaborador");

                            b1.WithOwner()
                                .HasForeignKey("ColaboradorModelId");
                        });

                    b.Navigation("ColaboradorCPF");

                    b.Navigation("Funcao");

                    b.Navigation("Nome");
                });
#pragma warning restore 612, 618
        }
    }
}
