// <auto-generated />
using Autenticacao.Infra.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Autenticacao.Infra.EF.Migrations
{
    [DbContext(typeof(AutenticacaoContext))]
    partial class AutenticacaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Autenticacao.Business.Models.UsuarioDoSistemaModel", b =>
                {
                    b.Property<string>("UsuarioIdentificador")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EhUsuarioAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("NomeUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioIdentificador");

                    b.ToTable("UsuarioDoSistema");
                });
#pragma warning restore 612, 618
        }
    }
}
